#!/bin/sh
reset

cur_dir=${PWD}
guiv=3
gui=gtk-${guiv}
config=0
build=0
install=0
src_dir=""
gitupdt=0
n_cpus=$(cat /proc/cpuinfo  | grep processor | wc -l)

configok=.config.ok
buildok=.build.ok

while getopts ":g:ucbis:" o; do
   case "${o}" in
      g)
         gui="${OPTARG}"
         ;;
      c)
         config=1
         ;;
      b)
         build=1
         ;;
      i)
         install=1
         ;;
      u)
         gitupdt=1
         ;;
      s)
         src_dir="${OPTARG}"
         ;;
      *)
         ;;
    esac
 done
shift $((OPTIND-1))

if [ ! -z ${src_dir} ]; then
   cd ${src_dir}
else 
   echo "src_dir empty (-s)"
   exit 1
fi


if [ ${gitupdt} -eq 1 ]; then
   git fetch --all --tags
   git pull
fi


if [ ${config} -eq 1 ]; then
   rm -fr ${configok} ${buildok}
   make clean distclean
   export CFLAGS="-Ofast -funroll-all-loops -fforward-propagate -foptimize-strlen -finline-functions-called-once -finline-small-functions -finline-functions"
   ./configure \
      --prefix=${HOME_NBCK}/usr/ \
      --with-features=huge \
      --enable-gui=${gui} \
      --enable-multibyte \
      --enable-terminal=no \
      --enable-xim \
      --with-tlib=ncurses \
      --with-x \
      --enable-fontset \
      --enable-autoservername \
      --disable-rightleft \
      --disable-arabic \
      --disable-farsi \
      --enable-gpm=yes \
      --enable-cscope \
      --with-tclsh=/usr/bin/tclsh \
      --with-gnome-includes=/usr/include/gtk-${gtkv}.0 \
      --with-gnome-libs=/usr/lib/x86_64-redhat-linux6E/ \
      --with-compiledby=simone.azzalin@kdpof.com 

   if [ $? -eq 0 ]; then
      touch ${configok}
   fi
fi

if [ -e ${configok} ]; then
   if [ ${build} -eq 1 ]; then
      make -j ${n_cpus}

      if [ $? -eq 0 ]; then
         touch ${buildok}
      fi
   fi
fi

if [ -e ${configok} ]; then
   if [ -e ${buildok} ]; then
      if [ ${install} -eq 1 ]; then
         make install
      fi
   fi
fi

cd ${cur_dir}
