#!/bin/sh
reset
make clean distclean
./configure \
   --prefix=/usr/local/ \
   --with-features=huge --enable-gui=gtk3 \
   --enable-multibyte --enable-terminal \
   --with-tlib=ncurses \
   --with-x  \
   --with-gnome-includes=/usr/include/gtk-3.0 \
   --with-gnome-libs=/usr/lib/x86_64-linux-gnu/ \
   --enable-pythoninterp=dynamic \
   --with-python-command=python \
   --with-lua-prefix=/usr/ \
   --with-compiledby=simone.azzalin@kdpof.com \
   --enable-luainterp=dynamic
# make -j 12
# make install
